### PR TITLE
osx-arm64 migration

### PR DESCRIPTION
**Pull request by mfansler**
Attempting to continue migration.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #19

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin, please rerender

**Comment by mfansler** [comment]
I suspect [the `configure` script's use `xml2-config`](https://github.com/r-lib/xml2/blob/ab2078976c9ab57116c7c9175632e7d19d45273f/configure#L26) to determine the `libxml2` location is messing with the cross-compiling. Fortunately, the script includes an option to override this behavior:

> ```
> # This script will query 'pkg-config' for the required cflags and ldflags.
> # If pkg-config is unavailable or does not find the library, try setting
> # INCLUDE_DIR and LIB_DIR manually via e.g:
> # R CMD INSTALL --configure-vars='INCLUDE_DIR=/.../include LIB_DIR=/.../lib'
> ```

Will attempt to use this override to with the `$PREFIX/lib` and `$PREFIX/include`. 

Also, shouldn't this recipe require `libxml2`? I suspect it's been fine since it is a `r-base` dependency, but it really is an immediate dependency for this package.

**Comment by mfansler** [comment]
Summarizing so far, none of these were the issue:

- `libxml2` dependency
-  use of `xml2-config`
- `configure.{guess,sub}`

Other idea is to see if we can tell R not to attempt loading the library when not running native. That is, the installation procedure appears to be attempting to load the library, which is problematic because the architecture mismatch.

**Comment by mfansler** [comment]
@colinbrislawn @conda-forge/r ready for review 🙏

Narrowed down the **osx-arm64** failure to the library self-loading while installing the `help`. For now, this skips the `help` installation in cross-compilation settings. I propose we release this for now (since other major R packages are waiting for this to be available), but open a separate issue to eventually get this built with a proper `help` documentation.

On the plus side, this recipe now runs the `testthat` unit tests on all native builds.

**Review by colinbrislawn — APPROVED** [review]
LGTM!

**Comment by mfansler** [comment]
@colinbrislawn ready to merge. I'll keep working on getting the help built (#24).

**Pull request merged**
