### PR TITLE
Fix metadata issue

### LINKED ISSUE #29: New R 4.3 builds not solveable
I'm unable to solve simple `r-base=4.3 r-xml2` for **linux-64** and this is blocking some R 4.3 migrations as "Not Solvable". I suspect this is due to `libxml2` listed under the `run:` requirements which overspecifies the version constraint. I'll send a PR.

<details>

```bash
$ CONDA_SUBDIR=linux-64 mamba create -n foo r-base=4.3 r-xml2     

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (1.4.2) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['r-base=4.3', 'r-xml2']

conda-forge/linux-64                                        Using cache
conda-forge/noarch                                          Using cache
bioconda/linux-64                                           Using cache
bioconda/noarch                                             Using cache
pkgs/main/linux-64                                            No change
pkgs/r/linux-64                                               No change
pkgs/r/noarch                                                 No change
Could not solve for environment specs
The following packages are incompatible
├─ r-base 4.3**  is installable with the potential options
│  ├─ r-base 4.3.0 would require
│  │  └─ libxml2 >=2.10.4,<2.11.0a0 , which can be installed;
│  └─ r-base 4.3.0 would require
│     └─ _r-mutex 1.* anacondar_1, which can be installed;
└─ r-xml2   is uninstallable because there are no viable options
   ├─ r-xml2 [1.0.0|1.1.1] would require
   │  └─ r-base 3.3.2*  but there are no viable options
   │     ├─ r-base 3.3.2 conflicts with any installable versions previously reported;
   │     └─ r-base [3.3.1|3.3.2|3.4.1] would require
   │        └─ icu 54.* , which does not exist (perhaps a missing channel);
   ├─ r-xml2 [1.1.1|1.2.0] would require
   │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] but there are no viable options
   │     ├─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
   │     └─ r-base 3.4.1 conflicts with any installable versions previously reported;
   ├─ r-xml2 1.2.0 would require
   │  └─ r-base >=3.5.1,<3.5.2.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 [1.2.0|1.2.1|...|1.3.2] would require
   │  └─ r-base >=3.5,<3.6.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 [1.2.0|1.2.1|...|1.3.2] would require
   │  └─ r-base >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 [1.3.2|1.3.3] would require
   │  └─ r-base >=4.0,<4.1.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 [1.3.2|1.3.3|1.3.4] would require
   │  └─ r-base >=4.1,<4.2.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 [1.3.3|1.3.4] would require
   │  └─ r-base >=4.2,<4.3.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 1.3.4 would require
   │  ├─ libxml2 >=2.11.4,<2.12.0a0 , which conflicts with any installable versions previously reported;
   │  └─ r-rcpp   but there are no viable options
   │     ├─ r-rcpp [0.12.10|0.12.13|0.12.15|0.12.16|0.12.8] would require
   │     │  └─ r-base 3.3.2*  but there are no viable options
   │     │     ├─ r-base 3.3.2 conflicts with any installable versions previously reported;
   │     │     └─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
   │     ├─ r-rcpp [0.12.10|0.12.11|...|1.0.0] would require
   │     │  └─ r-base [3.4.1* |>=3.4.1,<3.4.2.0a0 ] but there are no viable options
   │     │     ├─ r-base [3.3.1|3.3.2|3.4.1], which cannot be installed (as previously explained);
   │     │     └─ r-base 3.4.1 conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [0.12.17|0.12.18|1.0.0|1.0.1] would require
   │     │  └─ r-base >=3.5.1,<3.5.2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [1.0.1|1.0.2|1.0.3|1.0.4|1.0.4.6] would require
   │     │  └─ r-base >=3.5,<3.6.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [1.0.1|1.0.2|...|1.0.6] would require
   │     │  └─ r-base >=3.6,<3.7.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [1.0.4.6|1.0.5|...|1.0.9] would require
   │     │  └─ r-base >=4.0,<4.1.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [1.0.6|1.0.7|...|1.0.9] would require
   │     │  └─ r-base >=4.1,<4.2.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [1.0.10|1.0.9] would require
   │     │  └─ __glibc >=2.17,<3.0.a0 , which is missing on the system;
   │     ├─ r-rcpp [0.11.6|0.12.0] would require
   │     │  └─ r-base 3.2.0* , which does not exist (perhaps a missing channel);
   │     ├─ r-rcpp 0.12.0 would require
   │     │  └─ r-base 3.2.1* , which does not exist (perhaps a missing channel);
   │     ├─ r-rcpp [0.12.1|0.12.2] would require
   │     │  └─ r-base 3.2.2* , which does not exist (perhaps a missing channel);
   │     ├─ r-rcpp 0.12.13 would require
   │     │  └─ r-base >=3.4.2,<3.4.3a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [0.12.14|0.12.17|0.12.18] would require
   │     │  └─ _r-mutex 1.* mro_2, which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp 0.12.14 would require
   │     │  └─ r-base >=3.4.3,<3.4.4.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp 0.12.16 would require
   │     │  └─ r-base >=3.5.0,<3.5.1.0a0 , which conflicts with any installable versions previously reported;
   │     ├─ r-rcpp [0.12.5|0.12.8] would require
   │     │  └─ r-base 3.3.1* , which cannot be installed (as previously explained);
   │     └─ r-rcpp 1.0.8.3 would require
   │        └─ r-base >=4.2,<4.3.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 0.1.1 would require
   │  └─ r-base 3.2.0* , which does not exist (perhaps a missing channel);
   ├─ r-xml2 [0.1.1|0.1.2] would require
   │  └─ r-base 3.2.1* , which does not exist (perhaps a missing channel);
   ├─ r-xml2 0.1.2 would require
   │  └─ r-base 3.2.2* , which does not exist (perhaps a missing channel);
   ├─ r-xml2 [0.1.2|1.0.0] would require
   │  └─ r-base 3.3.1* , which cannot be installed (as previously explained);
   ├─ r-xml2 1.1.1 would require
   │  ├─ _r-mutex 1.* mro_2, which conflicts with any installable versions previously reported;
   │  └─ libxml2 >=2.9.7,<2.10.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 1.1.1 would require
   │  └─ r-base >=3.4.2,<3.4.3a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 1.1.1 would require
   │  └─ r-base >=3.4.3,<3.4.4.0a0 , which conflicts with any installable versions previously reported;
   ├─ r-xml2 1.2.0 would require
   │  ├─ _r-mutex 1.* mro_2, which conflicts with any installable versions previously reported;
   │  └─ libxml2 >=2.9.8,<2.10.0a0 , which conflicts with any installable versions previously reported;
   └─ r-xml2 1.2.0 would require
      └─ r-base >=3.5.0,<3.5.1.0a0 , which conflicts with any installable versions previously reported.
```

</details>

### PR DESCRIPTION
**Pull request by mfansler**
Closes #29.

## Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mfansler** [comment]
@conda-forge-admin please rerender

**Review by colinbrislawn — APPROVED** [review]
looks good to me

**Comment by colinbrislawn** [comment]
Looks good to me. Merge when ready

**Comment by mfansler** [comment]
No, it's still emitting incorrect metadata.

**Comment by mfansler** [comment]
While this does clean up the recipe a bit, it's not addressing anything practical. We can make these touch-ups in a proper bump.

**Pull request closed without merging**
